# .github/workflows/export-dependencies.yml
name: Export Dependencies

on:
  push:
    branches:
      - main
      - 'releases/**'

permissions:
  contents: write

jobs:
  export-deps:
    runs-on: ubuntu-latest
    permissions:
     contents: write
    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v3
        with:
          # persist the GITHUB_TOKEN so we can push later
          persist-credentials: true

      # 2. Setup Conda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"

      # 3. Install Python dependencies
      - name: Install Python Dependencies
        shell: bash -l {0}
        run: |
          # create/env or activate existing env
          if [ -f environment.yml ]; then
            conda env create -f environment.yml --name export-env || conda env update -f environment.yml --name export-env
          else
            conda create -y -n export-env python=3.10
          fi
          conda activate export-env
          # install pip reqs if you have them
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # 4. Export Python top-level deps
      - name: Export Python Dependencies
        shell: bash -l {0}
        run: |
          OUT=python-dependencies.txt
          echo "# Conda explicit history (only packages you requested)" > $OUT
          conda env export --from-history --no-builds | sed '1d' >> $OUT
          echo -e "\n# Pip top-level dependencies (not required by others)" >> $OUT
          pip list --not-required --format=freeze >> $OUT

      # 5. Commit & push back if changed
      - name: Commit dependency exports
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add python-dependencies.txt
          # (uncomment if you also export node deps)
          # git add node-dependencies.json
          if git diff --cached --quiet; then
            echo "No changes to dependency exports."
          else
            git commit -m "chore: update exported dependencies"
            git push
          fi

      # # 5. Setup Node.js
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "18"

      # # 6. Install Node.js deps
      # - name: Install Node.js Dependencies
      #   run: npm ci

      # # 7. Export Node.js full dependency tree
      # - name: Export Node.js Dependencies
      #   run: npm ls --all --json > node-dependencies.json

      # # 8. Commit & push back if changed
      # - name: Commit dependency exports
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add python-dependencies.txt node-dependencies.json
      #     if git diff --cached --quiet; then
      #       echo "No changes to dependency exports."
      #     else
      #       git commit -m "chore: update exported dependencies"
      #       git push
      #     fi
